version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homelibrary
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest-app
    restart: always
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
