version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homelibrary
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    restart: always
    container_name: nest-app
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    env_file:
      - .env
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
